import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "// Rul-8",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-tr from-black to-neutral-800 bg-no-repeat min-h-screen">
        {children}
      </body>
    </html>
  );
}
